services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: learning_platform
      POSTGRES_USER: ${DB_USER:-learning_platform}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-learning_platform}


    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U learning_platform"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: